version: '3'

services:
  docker-mysql:
    image: mariadb:10.5.8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3707:3306

  app:
    image: forhadmethun/shopping:latest
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/testdb?autoReconnect=true&useSSL=false
    depends_on:
      - docker-mysql
